### ISSUE TITLE
Slightly off-integer image scaling on Wii

### ISSUE THREAD

**Issue by vaguerant** [JeffRuLz/OpenHCL#6]
I have this "fixed" on my end but my fix is just the result of trial and error futzing around with these values, I'm certain it could be fixed far more correctly.

https://github.com/JeffRuLz/OpenHCL/blob/3c5cd814e711473e12c752d3b79fcf6093a8a8e4/platform/wii/source/graphics.cpp#L598-L599

https://github.com/JeffRuLz/OpenHCL/blob/3c5cd814e711473e12c752d3b79fcf6093a8a8e4/platform/wii/source/graphics.cpp#L660-L661

Locally, I made all of these `+ (0.03f / (f32)s-> ...` (plus, not minus, and `0.03f`, not `0.001f`).

The tilemap change should be apparent everywhere as long as you look close enough, while the DrawSurfacePart is more specific and only noticeable when objects are positioned on the scaling "seams". The room I found most useful for testing is this one:

![IMG_20201028_163617_620](https://user-images.githubusercontent.com/5259025/97421944-38c6b200-1961-11eb-8e33-2ea2b62dd04a.jpg)

If you look closely, there is a column of doubled pixels to the right of center of the screen, and a row of doubled pixels at the top of the left floating platform, including the top pixel of the floating platform itself.

Another example is this bat (with a stretched left eye), two screens to the left when starting a new game:

![IMG_20201028_173824_795](https://user-images.githubusercontent.com/5259025/97422205-9d820c80-1961-11eb-92d3-344075014c22.jpg)

Sorry I don't have a proper fix for this, it's an odd one. Both of the above examples are fixed with my jank hack, but I don't know whether I'm breaking anything else by doing that.

**Comment by JeffRuLz** [comment]
Fixed in https://github.com/JeffRuLz/OpenHCL/commit/855e0347ff9927b3e7b1379a60c659e78a7370a7
Also for what it's worth, I got the 0.001f value from [GRRLIB](https://github.com/GRRLIB/GRRLIB/blob/master/GRRLIB/GRRLIB/GRRLIB_render.c#L272).
